name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCR_REGION: australia-southeast1
  SERVICE_NAME: financial-analyst
  IMAGE_NAME: financial-analyst

jobs:
  test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run tests
        run: |
          pytest tests/ || echo "No tests found, skipping..."

  build-and-push:
    name: Build and Push to GCR
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker credentials for Artifact Registry
        run: |
          gcloud auth configure-docker australia-southeast1-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          docker build -t financial-analyst:latest .
          docker tag financial-analyst:latest australia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/financial-analyst-repo/financial-analyst:${{ github.sha }}
          docker tag financial-analyst:latest australia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/financial-analyst-repo/financial-analyst:latest

      - name: Push Docker image
        run: |
          docker push australia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/financial-analyst-repo/financial-analyst:${{ github.sha }}
          docker push australia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/financial-analyst-repo/financial-analyst:latest

  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            --platform managed \
            --region ${{ env.GCR_REGION }} \
            --allow-unauthenticated \
            --port 8501 \
            --memory 2Gi \
            --cpu 2 \
            --timeout 300 \
            --set-secrets OPENAI_API_KEY=OPENAI_API_KEY:latest,MARKETAUX_API_KEY=MARKETAUX_API_KEY:latest,OPENBB_PAT=OPENBB_PAT:latest,EMAIL_SENDER=EMAIL_SENDER:latest,EMAIL_PASSWORD=EMAIL_PASSWORD:latest,SMTP_SERVER=SMTP_SERVER:latest,SMTP_PORT=SMTP_PORT:latest,AZURE_POSTGRES_PASSWORD=AZURE_POSTGRES_PASSWORD:latest

      - name: Show deployment URL
        run: |
          gcloud run services describe ${{ env.SERVICE_NAME }} --platform managed --region ${{ env.GCR_REGION }} --format 'value(status.url)'