name: Example CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Requirements.txt
          pip install flake8 pytest

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        continue-on-error: true

      - name: Run tests
        run: |
          echo "No tests defined yet"
        continue-on-error: true

  build-and-push:
    name: Build and Push to GCR
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: YOUR_PROJECT_ID
          service_account_key: YOUR_SERVICE_ACCOUNT_KEY
          export_default_credentials: true

      - name: Configure Docker to use gcloud as credential helper
        run: |
          gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build \
            -t gcr.io/YOUR_PROJECT_ID/YOUR_IMAGE_NAME:latest \
            .

      - name: Push Docker image to GCR
        run: |
          docker push gcr.io/YOUR_PROJECT_ID/YOUR_IMAGE_NAME:latest

      - name: Output image details
        run: |
          echo "Image pushed successfully!"
          echo "Image URL: gcr.io/YOUR_PROJECT_ID/YOUR_IMAGE_NAME:latest"

  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: YOUR_PROJECT_ID
          service_account_key: YOUR_SERVICE_ACCOUNT_KEY
          export_default_credentials: true

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy YOUR_SERVICE_NAME \
            --image gcr.io/YOUR_PROJECT_ID/YOUR_IMAGE_NAME:latest \
            --platform managed \
            --region YOUR_REGION \
            --allow-unauthenticated \
            --memory 2Gi \
            --cpu 2 \
            --timeout 300 \
            --max-instances 10 \
            --min-instances 0

      - name: Get service URL
        run: |
          SERVICE_URL=$(gcloud run services describe YOUR_SERVICE_NAME \
            --platform managed \
            --region YOUR_REGION \
            --format 'value(status.url)')
          echo "Service deployed successfully!"
          echo "Service URL: $SERVICE_URL"
          echo "SERVICE_URL=$SERVICE_URL" >> $GITHUB_ENV

      - name: Create deployment summary
        run: |
          echo "## Deployment Summary :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Service Name**: YOUR_SERVICE_NAME" >> $GITHUB_STEP_SUMMARY
          echo "- **Region**: YOUR_REGION" >> $GITHUB_STEP_SUMMARY
          echo "- **Image**: gcr.io/YOUR_PROJECT_ID/YOUR_IMAGE_NAME:latest" >> $GITHUB_STEP_SUMMARY
          echo "- **Service URL**: $SERVICE_URL" >> $GITHUB_STEP_SUMMARY
          echo "- **Deployment Time**: $(date)" >> $GITHUB_STEP_SUMMARY